name: Build Windows Client

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: 'C:\vcpkg'

    steps:
    - uses: actions/checkout@v4

    - name: Cache vcpkg and CMake _deps
      uses: actions/cache@v4
      with:
        path: |
          C:\vcpkg\installed
          C:\Users\runneradmin\AppData\Local\vcpkg\archives
          build/_deps
        key: ${{ runner.os }}-cpp-cache-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cpp-cache-

    # On utilise le vcpkg intégré à l'image windows-latest de GitHub Actions
    - name: Integrate vcpkg
      run: |
        vcpkg integrate install
        vcpkg install openssl:x64-windows zlib:x64-windows

    - name: Configure CMake
      run: |
        cmake -B build -S . `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_TOOLCHAIN_FILE="${env:VCPKG_ROOT}\scripts\buildsystems\vcpkg.cmake" `
          -DUSE_TLS=ON -DUSE_OPEN_SSL=ON -DUSE_MBED_TLS=OFF -DUSE_WS=ON -DUSE_ZLIB=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Compile Installer (Inno Setup)
      run: iscc installer.iss

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: focworld_tcg_windows_setup
        path: Output/FOCWorld_TCG_Setup.exe
